import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { BookOpen, Brain, Star, Trophy, Sparkles, Zap } from "lucide-react";

export default function Landing() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-primary/5 via-background to-background">
      {/* Hero Section */}
      <section className="relative overflow-hidden py-20 px-4 sm:px-6 lg:px-8">
        <div className="absolute inset-0 bg-gradient-to-br from-primary/10 via-accent/5 to-transparent pointer-events-none" />
        <div className="max-w-6xl mx-auto text-center relative z-10">
          <div className="inline-flex items-center gap-2 bg-primary/10 px-4 py-2 rounded-full mb-6">
            <Sparkles className="w-4 h-4 text-primary" />
            <span className="text-sm font-semibold text-primary">AI-Powered Learning</span>
          </div>
          
          <h1 className="text-5xl sm:text-6xl lg:text-7xl font-bold mb-6 bg-gradient-to-r from-primary via-primary/80 to-primary/60 bg-clip-text text-transparent">
            SmartLearn NZ
          </h1>
          
          <p className="text-xl sm:text-2xl text-muted-foreground mb-4 max-w-3xl mx-auto">
            Interactive AI education for Kiwi kids
          </p>
          
          <p className="text-lg text-muted-foreground mb-8 max-w-2xl mx-auto">
            Personalized maths and English practice aligned with the New Zealand curriculum.
            Make learning fun with gamification, instant feedback, and adaptive AI questions!
          </p>
          
          <div className="flex flex-wrap gap-4 justify-center">
            <Button
              size="lg"
              className="text-lg px-8"
              onClick={() => window.location.href = "/api/login"}
              data-testid="button-start-learning"
            >
              <Star className="w-5 h-5 mr-2" />
              Start Learning Free
            </Button>
            <Button
              size="lg"
              variant="outline"
              className="text-lg px-8 bg-background/50 backdrop-blur-sm"
              data-testid="button-parent-login"
              onClick={() => window.location.href = "/api/login"}
            >
              <BookOpen className="w-5 h-5 mr-2" />
              Parent Login
            </Button>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-16 px-4 sm:px-6 lg:px-8">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-3xl sm:text-4xl font-bold text-center mb-12">
            Why kids love SmartLearn
          </h2>
          
          <div className="grid md:grid-cols-3 gap-6">
            <Card className="border-primary/20 hover-elevate active-elevate-2">
              <CardContent className="p-6">
                <div className="w-12 h-12 rounded-full bg-primary/10 flex items-center justify-center mb-4">
                  <Brain className="w-6 h-6 text-primary" />
                </div>
                <h3 className="text-xl font-semibold mb-2">AI-Powered Questions</h3>
                <p className="text-muted-foreground">
                  Get unlimited practice questions generated by AI, perfectly matched to your
                  year level and the NZ curriculum.
                </p>
              </CardContent>
            </Card>

            <Card className="border-accent/20 hover-elevate active-elevate-2">
              <CardContent className="p-6">
                <div className="w-12 h-12 rounded-full bg-accent/10 flex items-center justify-center mb-4">
                  <Trophy className="w-6 h-6 text-chart-3" />
                </div>
                <h3 className="text-xl font-semibold mb-2">Gamified Learning</h3>
                <p className="text-muted-foreground">
                  Earn points, unlock badges, build streaks, and celebrate achievements as you
                  master new skills!
                </p>
              </CardContent>
            </Card>

            <Card className="border-chart-2/20 hover-elevate active-elevate-2">
              <CardContent className="p-6">
                <div className="w-12 h-12 rounded-full bg-chart-2/10 flex items-center justify-center mb-4">
                  <Zap className="w-6 h-6 text-chart-2" />
                </div>
                <h3 className="text-xl font-semibold mb-2">Instant Feedback</h3>
                <p className="text-muted-foreground">
                  Get encouraging AI feedback immediately. Learn from mistakes with helpful
                  explanations and tips!
                </p>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      {/* Subjects Section */}
      <section className="py-16 px-4 sm:px-6 lg:px-8 bg-muted/30">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-3xl sm:text-4xl font-bold text-center mb-12">
            Practice Core Subjects
          </h2>
          
          <div className="grid md:grid-cols-2 gap-8 max-w-4xl mx-auto">
            <Card className="border-2 border-primary/30 hover-elevate active-elevate-2">
              <CardContent className="p-8 text-center">
                <div className="text-6xl mb-4">🔢</div>
                <h3 className="text-2xl font-bold mb-3">Maths</h3>
                <p className="text-muted-foreground mb-4">
                  Addition, subtraction, multiplication, division, fractions, decimals, and more!
                </p>
                <div className="text-sm text-muted-foreground">Years 1-8</div>
              </CardContent>
            </Card>

            <Card className="border-2 border-accent/30 hover-elevate active-elevate-2">
              <CardContent className="p-8 text-center">
                <div className="text-6xl mb-4">📚</div>
                <h3 className="text-2xl font-bold mb-3">English</h3>
                <p className="text-muted-foreground mb-4">
                  Reading comprehension, vocabulary, grammar, spelling, and creative writing!
                </p>
                <div className="text-sm text-muted-foreground">Years 1-8</div>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto text-center">
          <h2 className="text-3xl sm:text-4xl font-bold mb-4">
            Ready to start your learning journey?
          </h2>
          <p className="text-lg text-muted-foreground mb-8">
            Join thousands of Kiwi kids learning smarter every day!
          </p>
          <Button
            size="lg"
            className="text-lg px-8"
            onClick={() => window.location.href = "/api/login"}
            data-testid="button-get-started"
          >
            <Sparkles className="w-5 h-5 mr-2" />
            Get Started Now
          </Button>
        </div>
      </section>
    </div>
  );
}
